export {default as Navbar} from './Navbar'
export {default as Education} from './Education'
export {default as Experience} from './Experience'
export {default as ContactMe} from './ContactMe'
export {default as Projects} from './Projects'
export {default as AboutMe} from './AboutMe'